### PR TITLE
Here's a pull request in the other direction

### PR DESCRIPTION
**Pull request by scichelli**

### CODE REVIEW

**Review by mudspringhiker — COMMENTED** [review]
great

**Comment by mudspringhiker** [comment]
merged.  is that all i do? sorry. :-)

**Comment by mudspringhiker** [comment]
I think it is. so now I git pulled to my local.

**Comment by scichelli** [comment]
Yep, you got it. :) Is it all making sense?

**Comment by mudspringhiker** [comment]
yes, thanks! 😀 the new things I learned were pulling from another repo
(upstream) from which I originally forked it from, merging (I did try
merging before but it wasn't very clear, now it is clearer), git gui and
gitk (I'm used to doing git add and git commit on bash and I kind of missed
some of the explanations for git gui and gitk because I was messaging
someone having trouble during the workshop, hehe, but I will try to
understand it in my own time). For sure if I use git more for
collaboration, I will encounter more "huh?" problems, but at least I have a
better idea now. Thank you very much!

**Comment by scichelli** [comment]
:) What I was suggesting `git gui` for, is to replace the `git add -A` step and the `git commit -m 'msg'` step. The reason is that you can look at, and select, exactly which files you are going to commit, and look at the changes in each of those files before committing them. The equivalent to `git add` is to click the little doc icon next to a doc in the top left panel. That pops it down to the bottom left panel (which is "staging" the file). Only things in the bottom left will get committed. Put a comment in the lower right box, and click the Commit button. 

`gitk` is a history viewer.

**Pull request merged**
